//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_user_name { get; set; }
        public string admin_password { get; set; }
        public string admin_contact_number { get; set; }
        public string admin_email { get; set; }
        public Nullable<System.DateTime> admin_created_date { get; set; }
    }
}
