//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class computers
    {
        public int computer_id { get; set; }
        public string computer_name { get; set; }
        public string computer_location { get; set; }
        public string computer_ip { get; set; }
    }
}
